on:
  workflow_dispatch:
    
uses:
  actions/checkout@v2
  actions/upload-artifact@v2

run: 
  mkdir -p slack-digest
  echo hello > slack-digest/world.txt

with:
  name: my-artifact
  path: slack-digest/world.txt
