steps:
- uses: actions/checkout@v2

- run: mkdir -p slack-digest

- run: echo hello > slack-digest/world.txt

- uses: actions/upload-artifact@v2
  with:
    name: my-artifact
    path: slack-digest/world.txt
